build: ci test

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -35,62 +35,61 @@ jobs:
           version: v1.60
           args: -v --timeout=5m
   
-  test:
-    runs-on: ubuntu-latest-128
-    permissions: 
-      pull-requests: write
-    outputs:
-      failures: ${{ steps.generate-job-summary.outputs.failures }}
-    steps:
-    - name: checkout code
-      uses: actions/checkout@v4
-    - name: install Go
-      uses: actions/setup-go@v5
-      with:
-        go-version: 1.23.x
+  # test:
+  #   runs-on: ubuntu-latest-128
+  #   permissions: 
+  #     pull-requests: write
+  #   outputs:
+  #     failures: ${{ steps.generate-job-summary.outputs.failures }}
+  #   steps:
+  #   - name: checkout code
+  #     uses: actions/checkout@v4
+  #   - name: install Go
+  #     uses: actions/setup-go@v5
+  #     with:
+  #       go-version: 1.23.x
 
-    - name: install deps
-      run: |
-        go install golang.org/x/tools/cmd/goimports@latest && go install github.com/klauspost/asmfmt/cmd/asmfmt@latest
-        go install github.com/consensys/gnark-solidity-checker@v0.1.0
-        go install github.com/ethereum/go-ethereum/cmd/abigen@v1.14.8
-        sudo add-apt-repository ppa:ethereum/ethereum
-        sudo apt-get update
-        sudo apt-get install solc
+  #   - name: install deps
+  #     run: |
+  #       go install golang.org/x/tools/cmd/goimports@latest && go install github.com/klauspost/asmfmt/cmd/asmfmt@latest
+  #       go install github.com/consensys/gnark-solidity-checker@v0.1.0
+  #       go install github.com/ethereum/go-ethereum/cmd/abigen@v1.14.8
+  #       sudo add-apt-repository ppa:ethereum/ethereum
+  #       sudo apt-get update
+  #       sudo apt-get install solc
     
-    # Install gotestfmt on the VM running the action.
-    - name: Set up gotestfmt
-      uses: gotesttools/gotestfmt-action@v2
-      with:
-        # Optional: pass GITHUB_TOKEN to avoid rate limiting.
-        token: ${{ secrets.GITHUB_TOKEN }}
+  #   # Install gotestfmt on the VM running the action.
+  #   - name: Set up gotestfmt
+  #     uses: gotesttools/gotestfmt-action@v2
+  #     with:
+  #       # Optional: pass GITHUB_TOKEN to avoid rate limiting.
+  #       token: ${{ secrets.GITHUB_TOKEN }}
 
-    # Run tests with nice formatting. Save the original log in /tmp/gotest.log
-    - name: Run tests
-      run: |
-        set -euo pipefail
-        go test -json -v -p 4 -short -timeout=30m ./... 2>&1 | gotestfmt -hide=all | tee /tmp/gotest.log
-        go test -json -v -p 4 -tags=release_checks,solccheck . 2>&1 | gotestfmt -hide=all | tee -a /tmp/gotest.log
-        go test -json -v -p 4 -tags=prover_checks ./test/... 2>&1 | gotestfmt -hide=all | tee -a /tmp/gotest.log
-        go test -json -v -p 4 -tags=prover_checks ./examples/... 2>&1 | gotestfmt -hide=all | tee -a /tmp/gotest.log
-        go test -json -v -run=NONE -fuzz=FuzzIntcomp -fuzztime=30s ./internal/backend/ioutils 2>&1 | gotestfmt -hide=all | tee -a /tmp/gotest.log
+  #   # Run tests with nice formatting. Save the original log in /tmp/gotest.log
+  #   - name: Run tests
+  #     run: |
+  #       set -euo pipefail
+  #       go test -json -v -p 4 -short -timeout=30m ./... 2>&1 | gotestfmt -hide=all | tee /tmp/gotest.log
+  #       go test -json -v -p 4 -tags=release_checks,solccheck . 2>&1 | gotestfmt -hide=all | tee -a /tmp/gotest.log
+  #       go test -json -v -p 4 -tags=prover_checks ./test/... 2>&1 | gotestfmt -hide=all | tee -a /tmp/gotest.log
+  #       go test -json -v -p 4 -tags=prover_checks ./examples/... 2>&1 | gotestfmt -hide=all | tee -a /tmp/gotest.log
+  #       go test -json -v -run=NONE -fuzz=FuzzIntcomp -fuzztime=30s ./internal/backend/ioutils 2>&1 | gotestfmt -hide=all | tee -a /tmp/gotest.log
 
-    - name: Generate job summary
-      id: generate-job-summary
-      if: ${{ always() }}
-      run: |
-        if [ -s /tmp/gotest.log ]; then
-          cat /tmp/gotest.log > $GITHUB_STEP_SUMMARY
-          echo "failures=$(cat /tmp/gotest.log | node .github/parse-tests.js)" > $GITHUB_OUTPUT
-        else
-          echo "## Success ✅" > $GITHUB_STEP_SUMMARY
-          echo "failures=" > $GITHUB_OUTPUT
-        fi
+  #   - name: Generate job summary
+  #     id: generate-job-summary
+  #     if: ${{ always() }}
+  #     run: |
+  #       if [ -s /tmp/gotest.log ]; then
+  #         cat /tmp/gotest.log > $GITHUB_STEP_SUMMARY
+  #         echo "failures=$(cat /tmp/gotest.log | node .github/parse-tests.js)" > $GITHUB_OUTPUT
+  #       else
+  #         echo "## Success ✅" > $GITHUB_STEP_SUMMARY
+  #         echo "failures=" > $GITHUB_OUTPUT
+  #       fi
 
   slack-notifications:
     if: always()
     needs:
-      - staticcheck
       - test
     uses: ./.github/workflows/slack-notifications.yml
     with:
